language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
services:
- postgresql
script:
- './manage.py test'
deploy:
  provider: heroku
  api_key:
    secure: EuDlvUuLpRXGmIade93IsLXy6LUa2wuhMAVJzAjjLvWG3CSG2HdtLI0wsUbeCZd/9yjosgVuJWEl8L5GIQBzSLA70xMkVxjcjSrOtZC8woUDO9lJdrTyFxReugkEFLc8h/mQ7UrUaG2vmlBWu6b7efx6xm/YJr0m15n02BPr2h6CWztKIQi2ZtvkdQO9LstcN0w8lBVj5+ONX09KN+bVfNB992mEFG+fp4AdfssNtbGLSOr51CDxDAKc0p05kBce580imtHqH/iQGf59hCGVWREUkX204GwDTS/v0uIkO0CODpynig3N+v0f9lUlk2T16neGpx6ETRAvvX/WytvPjcRUQ9VDbtjey+1Qj5SrYdwODp1i/dl025tKR4UcPNHLCOKI38DoYCI4F/43NxAXZvWakC/6AOfZZjiFOsvGvx77ucTQBySX0vWcCnboE26p5R3LFjCwYYn+6XdVrpGgP+m9LXqjKgMU0kSspxVT4qJHRyolwvS02HfHuRM8yGnGqKcDK738LgN8M36/ac9vMurwLqnGzQ89XmdfqsT0T2zCDQ65LnnG9gROjUpIxbi0b2lyHj9s8v3zA/d6oBb5sGfBy6wR1TntDMBquHeu7op6oCo4TzXh3a/0Wg+wJBCLq2m/u/ASimcgW0THElk5oJ2WLrigUKG9UCBc7kJSif8=
  on:
    all_branches: true  
  app: olympic-analytics-tracker-db
  run: python manage.py migrate
