language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
services:
- postgresql
script:
- "./manage.py test"
deploy:
  provider: heroku
  api_key:
    secure: 3ZXKjtjLd9JgbXYYYyC0Sc8P3rgjyg6Y7F1vpVT1fo3EVxltLWv340o20M3W352kQWmWZ/R/OL6R+SfBhLF8Zp2MnuJy6ujpz+xjyd7PgBGNCpCW35W032kSOsQpvZ+Wast8oUCMJI+3htPkKrEShkR9fvMwfGU9eo6Ol0Ga/p0wrEZ1tTepdz7CTIOGdUqEVb0BDQ9hzU4T4zlK6PNC4M2uMPMbj6ZnqX1YXLByovB6twpBU8vvxxaKfgqScBJEBWc07z4BHuo8G6TMJrCJGIUD29uNw/217C5SyzaDNErbN++bxgQavmt9ZVete8HU5jQp43/f1WX0gcrMRDtepEPo8WFk0nCOMGNR5d2kBxfql7FtOFe2kErOrg6KEnF8TdbrHjHZbg4dI9VpAO3o8Qte87IEEOdk0l1ecGyYtj/WQDbVO9dWQi3/BhJpv1DFUK85eBhvEEVyOHYSjoJqjly+EUwiaKqdOJapanhOSVSKIUkYVJunNPPZh35uFTlugcFYFe5K88O5AI97YXcsSJCGYNlz7ljsIyxdd0dmYhlv/qfbOwJ+0uQWJ2X2eD4Ru4AsQoCb5qrWchKWFeXhwWFgjybiuYwS+Ci2Jnh9mAc3aZC+hCQRT1eAK800wkRqOO2vFt88Os2MO1XOOFarE8zYdkb/mOexNta0kje5lhQ=
  app: olympic-analytics-tracker-db
  on: main
  run: python manage.py migrate
